services:
    _defaults:
        autowire: true
        autoconfigure: true


    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
        


    App\Service\ServerDataService:
        arguments:
            $filePath: '%kernel.project_dir%/LeaseWeb_servers_filters_assignment[58].xlsx'

